name: Pacman Contributions

on:
  schedule:
    - cron: '0 0 * * *' # se ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Pacman Graph
        run: |
          npx github-contribution-pacman -u ${{ github.repository_owner }} -o output/pacman-contribution-graph.svg
          
      - name: Commit and Push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add output/pacman-contribution-graph.svg
          git commit -m "Update Pacman graph"
          git push
