name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # se ejecuta una vez al día
  workflow_dispatch: # permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Generar animación Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kodergoq
          outputs: dist/snake.svg

      - name: Subir resultado a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
